name: flutter_mopub
description: A new Flutter plugin that uses native platform views to show mopub rewarded video ads.
version: 0.0.1
homepage: https://gitlab.com/topfreelancerdeveloper/flutter_mopub.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.topfreelancerdeveloper.flutter_mopub
    pluginClass: FlutterMopubPlugin