name: flutter_mopub
description: A new Flutter plugin that uses native platform views to show mopub rewarded video ads.
version: 0.1.0
homepage: https://gitlab.com/topfreelancerdeveloper/flutter_mopub.git

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ^1.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.topfreelancerdeveloper.flutter_mopub
        pluginClass: FlutterMopubPlugin
      ios:
        pluginClass: FlutterMopubPlugin